phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=893894210731.dkr.ecr.ap-south-1.amazonaws.com/cicd-pipeline
      - IMAGE_TAG=latest
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo $IMAGE_TAG

  build:
    commands:
      - REPOSITORY_URI=893894210731.dkr.ecr.ap-south-1.amazonaws.com/cicd-pipeline
      - IMAGE_TAG=latest
      - echo Building the Spring Boot application...
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Build completed.

  post_build:
    commands:
      - REPOSITORY_URI=893894210731.dkr.ecr.ap-south-1.amazonaws.com/cicd-pipeline
      - IMAGE_TAG=latest
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"cicd-pipeline","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
